# Generated by Django 5.2.17 on 2026-08-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LuluPrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lulu_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Our order reference sent to Lulu.",
                        max_length=100,
                    ),
                ),
                ("status", models.CharField(default="CREATED", max_length=30)),
                ("status_message", models.TextField(blank=True)),
                ("tracking_urls", models.JSONField(blank=True, default=list)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lulu_jobs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lulu print job",
                "ordering": ["-created_at"],
            },
        ),
    ]
