# Generated by Django 5.2.17 on 2026-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display position — the approved arrangement.",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        max_length=10,
                    ),
                ),
                (
                    "src",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary URL. Leave empty for a 'coming soon' tile.",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Artwork", "Artwork"),
                            ("Community", "Community"),
                            ("Speaking & Media", "Speaking & Media"),
                            ("professional development", "professional development"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
