# Generated by Django 5.2.17 on 2026-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable id used by the cart & price validation (e.g. 'book-ebook').",
                        unique=True,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text='Card label, e.g. "The Book" / "New · The 3rd Book"',
                        max_length=60,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("subtitle", models.CharField(blank=True, max_length=250)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pdf", "eBook (PDF — instant download)"),
                            ("paperback", "Paperback (physical)"),
                        ],
                        default="pdf",
                        max_length=12,
                    ),
                ),
                (
                    "format_label",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "eBook only · PDF — instant download"',
                        max_length=120,
                    ),
                ),
                (
                    "bonus",
                    models.CharField(
                        blank=True,
                        help_text="The extra line under the format.",
                        max_length=300,
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Price in cents — 999 = $9.99. THE source of truth for checkout.",
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary (or other) URL of the cover image.",
                    ),
                ),
                ("cta", models.CharField(default="Add to Cart — eBook", max_length=60)),
                (
                    "accent",
                    models.BooleanField(
                        default=False, help_text="Featured styling on the card."
                    ),
                ),
                ("coming_soon", models.BooleanField(default=False)),
                (
                    "lulu_url",
                    models.URLField(
                        blank=True,
                        help_text="If set, the card shows a 'Buy the Paperback on Lulu.com' button.",
                    ),
                ),
                (
                    "ebook_file_url",
                    models.URLField(
                        blank=True,
                        help_text="PRIVATE download link for fulfillment (never shown publicly).",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Shirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="e.g. 'shirt-1' — cart ids arrive as 'shirt-1--XL'.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text='e.g. "Design 01"', max_length=60)),
                (
                    "color",
                    models.CharField(
                        help_text='Colorway shown to buyers, e.g. "Royal Blue"',
                        max_length=40,
                    ),
                ),
                (
                    "swatch",
                    models.CharField(
                        default="#5B2A86",
                        help_text="Hex color for the little dot on the card.",
                        max_length=9,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Cloudinary URL of the shirt photo."
                    ),
                ),
                ("price_cents", models.PositiveIntegerField(default=2500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
