# Generated by Django 5.2.17 on 2026-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lulu_cover_url',
            field=models.URLField(blank=True, help_text='Public URL of the full wraparound cover PDF.'),
        ),
        migrations.AddField(
            model_name='product',
            name='lulu_interior_url',
            field=models.URLField(blank=True, help_text='Public URL of the interior PDF (Lulu downloads it).'),
        ),
        migrations.AddField(
            model_name='product',
            name='lulu_pod_package_id',
            field=models.CharField(blank=True, help_text='Lulu SKU, e.g. 0600X0900.BW.STD.CW.060UW444.MXX — get it from developers.lulu.com/price-calculator', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='Interior page count — used for Lulu cost quotes.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('pdf', 'eBook (PDF — instant download)'), ('paperback', 'Paperback (physical — printed by Lulu)'), ('hardcover', 'Hardcover (physical — printed by Lulu)')], default='pdf', max_length=12),
        ),
    ]
