# Generated by Django 5.2.17 on 2026-08-10 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_lulu_cover_url_product_lulu_interior_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_edition',
            field=models.ForeignKey(blank=True, help_text='Optional printed edition offered on this same card (e.g. link the eBook to its paperback).', limit_choices_to={'kind__in': ['paperback', 'hardcover']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.product'),
        ),
    ]
