# Generated by Django 5.2.17 on 2026-08-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_print_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_ebook',
            field=models.ForeignKey(blank=True, help_text='A free eBook delivered with this product (e.g. 7 Faith Moves™ with every book purchase).', limit_choices_to={'kind': 'pdf'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.product'),
        ),
    ]
