# Generated by Django 5.2.17 on 2026-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoachingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "anchor",
                    models.TextField(
                        help_text="The scripture quote, with quotation marks."
                    ),
                ),
                (
                    "anchor_ref",
                    models.CharField(
                        help_text='e.g. "— 2 Corinthians 5:17 (CEV)"', max_length=120
                    ),
                ),
                ("copy", models.TextField(help_text="The Mindset Shift paragraph.")),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="CommunityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(default="01", max_length=4)),
                ("title", models.CharField(max_length=120)),
                ("host", models.CharField(blank=True, max_length=200)),
                ("copy", models.TextField(blank=True)),
                (
                    "partners",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"name": "...", "role": "..."}]',
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "credit",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Helen Williams · CEO" (leave blank for none)',
                        max_length=160,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=60, unique=True)),
                ("value", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("global", "Global (nav / footer)"),
                            ("home", "Home"),
                            ("author", "Author"),
                            ("shop", "Shop"),
                            ("coaching", "7 Steps Coaching"),
                            ("community", "Community"),
                            ("gallery", "PT's Gallery"),
                            ("bookclub", "Brown Study Bookish Club™"),
                            ("contact", "Let's Talk!"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Which block of the page this text belongs to (e.g. 'hero').",
                        max_length=60,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The specific text within the section (e.g. 'heading').",
                        max_length=60,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Where this appears on the site (shown to help editing).",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Site text",
                "verbose_name_plural": "Site texts (every word on the site)",
                "ordering": ["page", "order", "section", "key"],
                "unique_together": {("page", "section", "key")},
            },
        ),
    ]
