# Generated by Django 5.2.17 on 2026-08-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (checkout created)"),
                            ("paid", "Paid"),
                            ("fulfilled", "Fulfilled"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "square_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "square_payment_link_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("payment_link_url", models.URLField(blank=True)),
                ("customer_name", models.CharField(blank=True, max_length=160)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=40)),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("total_cents", models.PositiveIntegerField(default=0)),
                ("has_physical", models.BooleanField(default=False)),
                (
                    "notified",
                    models.BooleanField(
                        default=False, help_text="Order email sent to Pacita."
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        help_text="Product slug or 'shirt-N--SIZE'.", max_length=100
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("is_physical", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
