# Generated by Django 5.2.17 on 2026-08-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, help_text='eBook download links emailed to the buyer.'),
        ),
    ]
